### ISSUE TITLE
Chuncks?

### ISSUE THREAD

**Issue by YomaDan** [Santinell/jrpc2#10]
How to send test request from Postman? Have veriants how to avoid chunks receive data?

**Comment by Santinell** [comment]
I have never used Postman. Chunks problem exists only for tcpTransport, because json-rpc v2 don't describe how to pack text data into binary.

**Comment by YomaDan** [comment]
Проблема в следующем, при использовании expressjs события при отправке запроса не встроенным клиентом не доходят методы в промежуточном обработчике не срабатывают на события onRead onEnd

**Comment by Santinell** [comment]
Можешь скинуть нерабочий пример? И какая версия nodejs

**Comment by YomaDan** [comment]
Могу. Немного позже. Закончить одну фиговину надо.
