### ISSUE TITLE
Submodule support

### ISSUE THREAD

**Issue by CCali93** [Santinell/jrpc2#4]
When creating more sophisticated method hierarchies in jrpc, the framework will overwrite methods.

For example:

```js
var rpcServer = new rpc.Server();

rpcServer.expose('module.subModule.method1', function(a, b) {
    return a + b;
});

rpcServer.expose('module.subModule.method2', function(a, b) {
    return a * b; //both methods with have this method body
});
```

I feel like this should be addressed for the more sophisticated use cases. Perhaps an interface like this:
```js
rpcServer.exposeModule('module', {
    'submodule': {
         method1: function(a, b) {
              return a + b;
         },
         method2: function(a, b) {
              return a * b;
         }
    }
});
```

If you like the idea I'd be more than happy to work on a PR for it.

**Comment by Santinell** [comment]
Support of submodules added. Now you can use both methods (expose or exposeModule)

**Comment by CCali93** [comment]
Wow dude that was quick! Thank you so much!
