### ISSUE TITLE
Issue with sending ID in response 

### ISSUE THREAD

**Issue by CCali93** [Santinell/jrpc2#5]
https://github.com/Santinell/jrpc2/blob/master/src/Server.coffee#L111-L115

```coffeescript
setSuccess = (result) ->
      response =
        jsonrpc: '2.0'
        result: result || null
        id: call.id || null
```

If ID is a number and has the value 0, then the expression `0 || null` will result in the value null instead of 0, which is what the server should respond with (According to [JSON RPC specs](http://www.jsonrpc.org/specification) the id should be parroted in the response).

Suggested code to fix:
```coffeescript
setSuccess = (result) ->
      response =
        jsonrpc: '2.0'
        result: result || null
        id: if typeof call.id is 'number' then call.id else (call.id || null)
```

Let me know if you want me to make a PR and test this change.

**Comment by Santinell** [comment]
Thanks
